config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :requests
    resources :admin_users
    resources :employees
    resources :payroll_records
    root to: "users#index"
  end

  resources :requests do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root "welcome#index"
end

app/views/shared/_admin_link_nav.html.erb
<li>
  <%= link_to 'Admin Dashboard', admin_root_path %>
</li>
<li class="divider"></li>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "HIG App Notification", sticky: false, time: 1000, image: :notice) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "HIG App Notification", sticky: false, time: 1000, image: :notice) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "HIG App Notification", sticky: false, time: 1000, image: :notice) %>
<% end %>

app/views/shared/_employee_items_nav.html.erb
<li class="<%= active?(requests_path) %>">
  <a href="/requests">Requests</a>
</li>

<li class="<%= active?(new_request_path) %>">
  <a href="/requests/new">Submit Punch Times</a>
</li>

app/views/shared/_manager_audit_log_nav.html.erb
<% if policy(AuditLog).index? %>
  <li class="<%= active?(audit_logs_path) %>">
    <a href="/audit_logs">Audit Log</a>
  </li>
<% end %>

app/views/shared/_nav.html.erb
<div class="logo">
  <h1>HIG EOM</h1>
</div>

<% if current_user %>
  <ul class="custom-nav nav nav-tabs">
    <li class="<%= active?(root_path) %>">
      <a href="/" class="glyphicon glyphicon-home"></a>
    </li>

    <%= render 'shared/employee_items_nav' if employee? %>
    <%= render 'shared/manager_audit_log_nav' if manager_or_admin? %>

    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
      <ul class="dropdown-menu">
        <%= render 'shared/admin_link_nav.html.erb' if manager_or_admin? %>
        <li>
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>