config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :requests
    resources :admin_users
    resources :employees
    resources :payroll_records
    root to: "users#index"
  end

  resources :requests do
    member do
      get :approve
    end
  end
  devise_for :users, skip: [:registrations]
  root "welcome#index"
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if admintypes.include?(current_user.type)
      @pending_requests = Request.submitted
      @recent_audits = AuditLog.last(10)
    else
      @pending_audit_confirmations = current_user.audit_logs.pending.by_start_date
    end
  end
end

app/views/welcome/_admin.html.erb
<div class="container-fluid">
  <!-- Pending Requests -->
  <div class="pending-posts request_approvals row">
    <h2>Requests Pending Approval</h2>
    <hr>
    <% @pending_requests.each do |pending_request| %>
      <div class="welcome-page-block col-md-3">
        <h5><%= pending_request.user.full_name %></h5>
        <p><span class="post-details">Submitted:</span><%= pending_request.date %></p>
        <p><span class="post-details">Work Summary:</span><%= truncate(pending_request.work_summary, length: 25) %></p>
        <div class="row">
          <div class="col-md-6 column">
            <%= link_to "Approve", approve_request_path(pending_request), class: 'btn btn-success btn-block', id: "#{pending_request.id}_approve" %>
          </div>
          <div class="col-md-6 column">
            <%= link_to "Review", edit_request_path(pending_request), class: 'btn btn-danger btn-block' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <hr>

  <div class="pending-posts audit_submissions row">
    <h2>Audit Logs For Submission</h2>
    <hr>
    <% @recent_audits.each do |audit| %>
      <div class="welcome-page-block col-md-3">
        <h5><%= audit.user.full_name %></h5>
        <p><span class="post-details">Audit Start Date: </span><%= audit.start_date %></p>
        <p><span class="post-details">Audit End Date: </span><%= audit.end_date || status_look('pending') %></p>
        <p><span class="post-details">Status: </span><%= status_look audit.status %></p>
      </div>
    <% end %>
    <div class="clearfix"></div>
    <hr>
    <%= link_to  "View all Audit Logs", audit_logs_path, class: "btn btn-primary btn-block" %>
  </div>
</div>

app/views/welcome/_employee.html.erb
<div class="container-fluid">
  <div class="row">
    <% if @pending_audit_confirmations.count > 0 %>
      <div class="pending-posts employee-blocks">
        <h3>Your Pending Audit Confirmations</h3>
        <% @pending_audit_confirmations.each do |pending_audit_confirmation| %>
          <%= link_to "I confirm that I haven't done any overtime between '#{pending_audit_confirmation.start_date}' and '#{pending_audit_confirmation.start_date.end_of_week}'", confirm_audit_log_path(pending_audit_confirmation), class: 'btn btn-primary btn-block btn-lg btn-for-emplyoee', id: "#{pending_audit_confirmation.id}_confirm", data: { confirm: 'Confirming this means you have no overtime in the mentioned days. Are you sure on confirming this?' } %>
        <% end %>
      </div>
    <% end %>

    <div class="pending-posts employee-blocks">
      <h3>Request Overtime</h3>
      <%= link_to 'Add Overtime Request', new_request_path, class: "btn btn-primary btn-block btn-lg"  %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<% if admintypes.include?(current_user.try(:type)) %>
  <%= render 'admin' %>
<% else %>
  <%= render 'employee' %>
<% end %>